name: Pipeline Revisão

on:
 push:
   branches:
     - main
jobs:
  build_and_deploy:
    runs-on: ubunto-lastest

    steps:
    -name: Fazendo clone do repo 
      -uses: actions/checkout@v3

      -name: configurando Python
      -uses: actions/setup-pytohn@v4

      -name: instalando dependendcias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      -name: Rodando os testes
       run: pytest
      
